# Generated by Django 5.2.4 on 2026-06-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_pixel_last_updated_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
